### ISSUE TITLE
Solicitud Acceso a Grace Tellez

### ISSUE THREAD

**Issue by tellezbnatalia** [zcrodriguez/AC_Taller2#1]
Qué tal, Colega. ¿Me podrías dar acceso a editar tu Branch?

**Comment by zcrodriguez** [comment]
¡Hola colega!
Me complace anunciarte que eres oficialmente colaboradora de este repositorio.

![image](https://github.com/zcrodriguez/AC_Taller2/assets/75572197/9c1b7730-8833-4665-9ccd-b6d8f191e1fd)
